apiVersion: v1
kind: Pod
metadata:
  name: @@NAME@@
  labels:
    app.kubernetes.io/name: vn2-hands-on
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux
    benchmark-path: @@PATH@@
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists
      effect: NoSchedule
  containers:
    - name: hands-on
      image: mcr.microsoft.com/azure-cli@sha256:0df3dcd6f4342770c2f0992c6c6552297fe8433195372fc2438a7c00bf3fd826
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - 'date -u +"HANDS_ON_PROCESS_STARTED=%Y-%m-%dT%H:%M:%S.%NZ"; touch /tmp/ready; sleep 600'
      resources:
        requests: {cpu: 500m, memory: 512Mi}
        limits: {cpu: "1", memory: 1Gi}
      readinessProbe:
        exec:
          command: ["/bin/sh", "-c", "test -f /tmp/ready"]
        periodSeconds: 1
        timeoutSeconds: 1
        failureThreshold: 30
